"""create tables

Revision ID: babedb684245
Revises: 
Create Date: 2022-10-19 15:11:37.121390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babedb684245'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('client_id', sa.String(length=256), nullable=False),
    sa.Column('client_tel', sa.String(length=256), nullable=False),
    sa.Column('default_amount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=256), nullable=False),
    sa.Column('client_id', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.client_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('places',
    sa.Column('client_id', sa.String(length=256), nullable=False),
    sa.Column('empty_amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.client_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    op.drop_table('customers')
    op.drop_table('users')
    # ### end Alembic commands ###
